
language: android
android:
        components:
                - platform-tools
                - build-tools-29.0.2
                - android-28
                - extra-android-m2repository
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
