language: android
env:
        global:
                - ANDROID_TARGET=android-29
                - ANDROID_ABI=armeabi-v7a
android:
        components:
                - platform-tools
                - build-tools-29.0.2
                - android-29
                - extra-android-m2repository
                - $ANDROID_TARGET
                - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
        - ./gradlew build jacocoTestReport assembleAndroidTest
        - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
        - emulator -avd test -no-skin -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
        - ./gradlew connectedCheck

before_install:
        - chmod +x gradlew

after_success:
        — bash <(curl -s https://codecov.io/bash) -t e3d308c9-738d-46fe-a0d0-139f8168c20d
