language: android
android:
        components:
                - platform-tools
                - build-tools-29.0.2
                - android-29
                - extra-android-m2repository

script:
        - ./gradlew build jacocoTestReport assembleAndroidTest

before_install:
        - chmod +x gradlew

after_success:
        — bash <(curl -s https://codecov.io/bash)
