package android.rad.shipment.calculator.view;

import android.content.Context;
import android.os.Bundle;
import android.rad.shipment.calculator.R;
import android.rad.shipment.calculator.base.BaseActivity;
import android.rad.shipment.calculator.presenter.MenuPresenter;
import android.rad.shipment.calculator.view.interfaces.MenuActivityViewInterface;
import android.view.View;

import androidx.annotation.NonNull;

public class MenuActivityView extends BaseActivity<MenuPresenter> implements MenuActivityViewInterface {
    @NonNull
    @Override
    protected MenuPresenter createPresenter(@NonNull Context context) { return new MenuPresenter(this); }

    @Override protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        /* setting the layout to show on the screen (most important)
         *
         * R = Resource Class (generated by the build system)
         * R.layout.activity_main = Resource object that represents the layout
         *     - getting the activity_main.xml file (similar to loading fxml file)
         *
         * takes the reference_layout layout and sets it to be the CurrentView (what is currently displayed on the screen)
         */
        setContentView(R.layout.menu_layout);

        final View logo = findViewById(R.id.imgViewColorLogo);
        final View shipmentBtn = findViewById(R.id.btnShipment);
        final View referenceBtn = findViewById(R.id.btnReference);

        OnMenuButtonsClicked onMenuButtonsClicked = new OnMenuButtonsClicked();

        logo.setOnClickListener(onMenuButtonsClicked);
        referenceBtn.setOnClickListener(onMenuButtonsClicked);
        shipmentBtn.setOnClickListener(onMenuButtonsClicked);
    }

    private class OnMenuButtonsClicked implements View.OnClickListener {
        @Override public void onClick(final View view) {
            switch (view.getId()) {
                case R.id.imgViewColorLogo:
                    mPresenter.onLogoClicked();
                    break;
                case R.id.btnShipment:
                    mPresenter.onShipmentButtonClicked();
                    break;
                case R.id.btnReference:
                    mPresenter.onReferenceButtonClicked();
                    break;
            }
        }
    }
}
