package android.rad.shipment.calculator.view;

import android.content.Context;
import android.os.Bundle;
import android.rad.shipment.calculator.R;
import android.rad.shipment.calculator.base.BaseActivity;
import android.rad.shipment.calculator.database.datasource.ShipmentCalculatorDataSource;
import android.rad.shipment.calculator.presenter.ReferencePresenter;
import android.rad.shipment.calculator.task.AppTaskExecutor;
import android.rad.shipment.calculator.view.interfaces.ReferenceActivityViewInterface;
import android.view.View;

import androidx.annotation.NonNull;

public class ReferenceActivityView extends BaseActivity<ReferencePresenter> implements ReferenceActivityViewInterface {

    @NonNull @Override
    protected ReferencePresenter createPresenter(@NonNull Context context) {
        return new ReferencePresenter(this,  new AppTaskExecutor(this), new ShipmentCalculatorDataSource(this));
    }

    @Override protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        /* setting the layout to show on the screen (most important)
         *
         * R = Resource Class (generated by the build system)
         * R.layout.activity_main = Resource object that represents the layout
         *     - getting the activity_main.xml file (similar to loading fxml file)
         *
         * takes the reference_layout layout and sets it to be the CurrentView (what is currently displayed on the screen)
         */
        setContentView(R.layout.reference_layout);

        final View menuBtn = findViewById(R.id.imgViewMenuBtn);
        final View searchView = findViewById(R.id.searchView);

        OnReferenceButtonsClicked onReferenceButtonsClicked = new OnReferenceButtonsClicked();

        menuBtn.setOnClickListener(onReferenceButtonsClicked);
    }

    private class OnReferenceButtonsClicked implements View.OnClickListener {
        @Override public void onClick(final View view) {
            switch (view.getId()) {
                case R.id.imgViewMenuBtn:
                    mPresenter.onMenuButtonClicked();
                    break;
            }
        }
    }
}
