package android.rad.shipment;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.rad.shipment.calculator.R;

public class MainActivity extends AppCompatActivity {

    @Override protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        /* setting the layout to show on the screen (most important)
         *
         * R = Resource Class (generated by the build system)
         * R.layout.activity_main = Resource object that represents the layout
         *     - getting the activity_main.xml file (similar to loading fxml file)
         *
         * takes the activity_main layout and sets it to be the CurrentView (what is currently displayed on the screen)
         */
        setContentView(R.layout.reference_layout);

    }
}
